#!/usr/bin/env bash

# https://www.shellcheck.net/wiki/SC1090
# shellcheck source=/dev/null
source "${1}"

echo "FG                : ${C_FG}"
echo "BG                : ${C_BG}"
echo "Hover FG          : ${C_HFG}"
echo "Hover BG          : ${C_HBG}"
echo "Cursor FG         : ${C_CFG}"
echo "Cursor BG         : ${C_CBG}"
echo "Black           00: ${C_00}"
echo "Light Black     08: ${C_08}"
echo "Grey            07: ${C_07}"
echo "Light Grey      15: ${C_15}"
echo "Red             01: ${C_01}"
echo "Light Red       09: ${C_09}"
echo "Green           02: ${C_02}"
echo "Light Green     10: ${C_10}"
echo "Yellow          03: ${C_03}"
echo "Light Yellow    11: ${C_11}"
echo "Blue            04: ${C_04}"
echo "Light Blue      12: ${C_12}"
echo "Purple          05: ${C_05}"
echo "Light Purple    13: ${C_13}"
echo "Turquoise       06: ${C_06}"
echo "Light Turquoise 14: ${C_14}"

echo "Gnome terminal profile palette: ${C_PAL}"

echo "Ptyxi like palette:"
# https://gitlab.gnome.org/chergert/ptyxis/-/tree/main/src/palettes?ref_type=heads

echo "Hover FG          : ${C_HFG}"
echo "Hover BG          : ${C_HBG}"
echo "Cursor BG         : ${C_CBG}"
echo "Background=${C_BG}"
echo "Foreground=${C_FG}"
echo "Cursor=${C_CFG}"
echo "Color0=${C_00}"   # Black           00
echo "Color1=${C_01}"   # Red             01
echo "Color2=${C_02}"   # Green           02
echo "Color3=${C_03}"   # Yellow          03
echo "Color4=${C_04}"   # Blue            04
echo "Color5=${C_05}"   # Purple          05
echo "Color6=${C_06}"   # Turquoise       06
echo "Color7=${C_07}"   # Grey            07
echo "Color8=${C_08}"   # Light Black     08
echo "Color9=${C_09}"   # Light Red       09
echo "Color10=${C_10}"  # Light Green     10
echo "Color11=${C_11}"  # Light Yellow    11
echo "Color12=${C_12}"  # Light Blue      12
echo "Color13=${C_13}"  # Light Purple    13
echo "Color14=${C_14}"  # Light Turquoise 14
echo "Color15=${C_15}"  # Light Grey      15
