#!/usr/bin/env bash

# https://www.shellcheck.net/wiki/SC1090
# shellcheck source=/dev/null
source "${1}"

echo "FG                : ${C_FG}"
echo "BG                : ${C_BG}"
echo "Hover FG          : ${C_HFG}"
echo "Hover BG          : ${C_HBG}"
echo "Cursor FG         : ${C_CFG}"
echo "Cursor BG         : ${C_CBG}"
echo "Black           00: ${C_00}"
echo "Light Black     08: ${C_08}"
echo "Grey            07: ${C_07}"
echo "Light Grey      15: ${C_15}"
echo "Red             01: ${C_01}"
echo "Light Red       09: ${C_09}"
echo "Green           02: ${C_02}"
echo "Light Green     10: ${C_10}"
echo "Yellow          03: ${C_03}"
echo "Light Yellow    11: ${C_11}"
echo "Blue            04: ${C_04}"
echo "Light Blue      12: ${C_12}"
echo "Purple          05: ${C_05}"
echo "Light Purple    13: ${C_13}"
echo "Turquoise       06: ${C_06}"
echo "Light Turquoise 14: ${C_14}"

echo "Gnome terminal profile palette: ${C_PAL}"
