#!/usr/bin/env bash

extensions=(
  amazonwebservices.aws-toolkit-vscode
  anweber.vscode-httpyac
  attilathedud.data-converter
  eamodio.gitlens
  editorconfig.editorconfig
  github.github-vscode-theme
  github.vscode-github-actions
  golang.go
  hashicorp.hcl
  hashicorp.terraform
  inferrinizzard.prettier-sql-vscode
  mitchdenny.ecdc
  ms-azuretools.vscode-docker
  ms-kubernetes-tools.vscode-kubernetes-tools
  ms-python.python
  ms-python.vscode-pylance
  ms-vscode-remote.remote-containers
  ms-vscode-remote.remote-ssh
  ms-vscode-remote.remote-ssh-edit
  ms-vscode.remote-explorer
  redhat.ansible
  redhat.vscode-xml
  redhat.vscode-yaml
  rust-lang.rust-analyzer
  sclu1034.justfile
  streetsidesoftware.code-spell-checker
  streetsidesoftware.code-spell-checker-greek
  tamasfe.even-better-toml
  tsandall.opa
  unifiedjs.vscode-mdx
  vscode-icons-team.vscode-icons
)

for ext in "${extensions[@]}"; do
  echo "Installing ${ext}"
  code --install-extension "${ext}"
done

unset extensions
unset ext
