#!/usr/bin/env bash

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONF_PATH="${HOME}/.config/Code/User"
if [[ $(uname) == "Darwin" ]]; then
  CONF_PATH="${HOME}/Library/Application Support/Code/User/"
fi
mkdir -p "${CONF_PATH}"

lnx "${SRC}/settings.json" "${CONF_PATH}/settings.json"

if [[ $(uname) == "Linux" ]]; then
  lnx "${SRC}/keybindings.json" "${CONF_PATH}/keybindings.json"
fi
