#!/usr/bin/env bash

apm install \
  atom-beautify \
  file-icons \
  highlight-selected \
  language-scala \
  linter \
  linter-ui-default \
  intentions \
  busy-signal \

#themes
# nord-atom-syntax
# nord-atom-ui

# nova-atom-syntax
# nova-atom-ui
