#!/usr/bin/env bash

path-abs() {
  local drnm="$(dirname $1)"
  echo $(cd -P $drnm && pwd)
}

path-real() {
  local SOURCE="$1"
  while [[ -L $SOURCE ]]; do
    local DIR="$(path-abs $SOURCE)"
    SOURCE="$(readlink --canonicalize-existing --no-newline $SOURCE)"
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
  done
  echo "$(path-abs $SOURCE)"
}

DIR="$(path-real ${BASH_SOURCE[0]})"

echo "********************************************************"
echo "**************** Marmalade Installation ****************"
echo "  marmalade folder: $DIR"

if [ ! -f ~/.marmalade.bash ]; then
  echo "  create symlink of marmalade.bash at home folder"
  ln -s $DIR/marmalade.bash ~/.marmalade.bash
else
  echo "  marmalade syslink exists"
fi

BASH_FILE=~/.bashrc
[[ ! -f $BASH_FILE ]] && BASH_FILE=~/.bash_profile
[[ ! -f $BASH_FILE ]] && touch $BASH_FILE
echo "  file to be used: $BASH_FILE"

SOURCE_LINE='[[ -r ~/.marmalade.bash ]] && [[ -f ~/.marmalade.bash ]] && source ~/.marmalade.bash'
if grep --fixed-strings --quiet "$SOURCE_LINE" $BASH_FILE; then
  echo "  marmalade sourcing is already included in $BASH_FILE"
else
  echo "  add marmalade sourcing in $BASH_FILE"
  echo $SOURCE_LINE >> $BASH_FILE
fi

echo "********************************************************"
echo "********************************************************"

unset DIR
unset BASH_FILE
unset SOURCE_LINE
unset -f rlpth
unset -f abspth
