#!/usr/bin/env bash

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONF_PATH="${HOME}/.config/bat"
# if [[ $(uname) = "Darwin" ]]; then
#   CONF_PATH="${HOME}/.config/bat"
# fi
mkdir -p "${CONF_PATH}"

SELF_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

lnx "${SRC}/config" "${CONF_PATH}/config"
