#!/usr/bin/env bash

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONF_PATH="${HOME}/.config/bat"
# if [[ $(uname) = "Darwin" ]]; then
#   CONF_PATH="${HOME}/.config/bat"
# fi
mkdir -p "${CONF_PATH}"

lnx "${SRC}/config" "${CONF_PATH}/config"
