#!/usr/bin/env bash


go get -u -v github.com/acroca/go-symbols
go get -u -v github.com/alecthomas/gometalinter
go get -u -v github.com/cweill/gotests/...
go get -u -v github.com/davidrjenni/reftools/cmd/fillstruct
go get -u -v github.com/fatih/gomodifytags
go get -u -v github.com/go-delve/delve/cmd/dlv
#go get -u -v github.com/golangci/golangci-lint/cmd/golangci-lint #
go get -u -v github.com/haya14busa/goplay/cmd/goplay
go get -u -v github.com/josharian/impl
#go get -u -v github.com/mdempsky/gocode #
go get -u -v github.com/mgechev/revive
go get -u -v github.com/posener/complete/gocomplete
go get -u -v github.com/ramya-rao-a/go-outline
go get -u -v github.com/rogpeppe/godef
go get -u -v github.com/sqs/goreturns
go get -u -v github.com/stamblerre/gocode #works with Go Modules.
#go get -u -v github.com/tpng/gopkgs #
go get -u -v github.com/uudashr/gopkgs/v2/cmd/gopkgs
go get -u -v github.com/zmb3/goaddimport
go get -u -v github.com/zmb3/gogetdoc
go get -u -v golang.org/x/lint/golint
go get -u -v golang.org/x/tools/cmd/godoc
go get -u -v golang.org/x/tools/cmd/goimports
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/gopls
#go get -u -v sourcegraph.com/sqs/goreturns #


gometalinter --install
gocomplete -install
