#!/usr/bin/env bash

#Helper function
gsettings-set() {
  setting=$1
  value=$2
  local old_value=$(gsettings get $1)
  gsettings set $1 "$2"
  echo "$setting: ${old_value} -> $(gsettings get $1)"
}

#Terminal colors
C_HFG="#FF4081"
C_HBG="#000A12"
C_FG="#F8F8F2"
C_BG="#282A36"
C_PAL="['#000000','#FF5555','#50FA7B','#F1FA8C','#BD93F9','#FF79C6','#8BE9FD','#BFBFBF','#4D4D4D','#FF6E67','#5AF78E','#F4F99D','#CAA9FA','#FF92D0','#9AEDFE','#E6E6E6']"

################### Gnome Terminal #############################################
echo ""
echo "----- Gnome Terminal Colors -----"
gdp=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
default_profile_path="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${gdp}/"

gsettings-set "${default_profile_path} foreground-color" "$C_FG"
gsettings-set "${default_profile_path} background-color" "$C_BG"
gsettings-set "${default_profile_path} highlight-foreground-color" "$C_HFG"
gsettings-set "${default_profile_path} highlight-background-color" "$C_HBG"
gsettings-set "${default_profile_path} palette" "$C_PAL"
echo "-----------------------------------"
################################################################################
