#!/usr/bin/env bash

gsettings-set() {
  setting=$1
  value=$2
  echo "Current value of $setting: $(gsettings get $1)"
  gsettings set $1 "$2"
  echo "New value of     $setting: $(gsettings get $1)"
  echo ""
}

tilix-default-profile() {
  gsettings get com.gexperts.Tilix.ProfilesList default | tr -d \'
}

gnome-terminal-default-profile() {
  gsettings get org.gnome.Terminal.ProfilesList default | tr -d \'
}


################### Gnome Shell and WM #########################################
gsettings-set "org.gnome.shell.keybindings focus-active-notification" "[]"
gsettings-set "org.gnome.shell.keybindings toggle-message-tray" "[]"
gsettings-set "org.gnome.desktop.wm.keybindings maximize-vertically" "['<Shift><Alt>r']"
gsettings-set "org.gnome.desktop.wm.keybindings switch-applications" "['<Super>Tab']"
gsettings-set "org.gnome.desktop.wm.keybindings switch-windows" "['<Alt>Tab']"
################################################################################


################### Gnome Terminal #############################################
gsettings-set "org.gnome.Terminal.Legacy.Settings default-show-menubar" "false"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ copy" "<Super>c"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ paste" "<Super>v"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ new-tab" "<Super>t"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ close-tab" "<Super>w"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ reset-and-clear" "<Super>r"
gsettings-set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gnome-terminal-default-profile)/ allow-bold" "false"
gsettings-set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gnome-terminal-default-profile)/ default-size-columns" "120"
gsettings-set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gnome-terminal-default-profile)/ default-size-rows" "30"
gsettings-set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gnome-terminal-default-profile)/ scrollback-unlimited" "true"
################################################################################


################### Tilix ######################################################
if [[ -x "$(command -v tilix)" ]]; then
  gsettings-set "com.gexperts.Tilix.Keybindings terminal-copy" "<Super>c"
  gsettings-set "com.gexperts.Tilix.Keybindings terminal-paste" "<Super>v"
  gsettings-set "com.gexperts.Tilix.Keybindings app-new-session" "<Super>t"
  gsettings-set "com.gexperts.Tilix.Keybindings session-close" "<Super>w"
  gsettings-set "com.gexperts.Tilix.Keybindings terminal-reset-and-clear" "<Super>r"
  gsettings-set "com.gexperts.Tilix.Settings use-overlay-scrollbar" "false"
  gsettings-set "com.gexperts.Tilix.Settings use-tabs" "true"
  gsettings-set "com.gexperts.Tilix.Settings unsafe-paste-alert" "false"
  gsettings-set "com.gexperts.Tilix.Settings terminal-title-style" "small"
  gsettings-set "com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/$(tilix-default-profile)/ default-size-columns" "120"
  gsettings-set "com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/$(tilix-default-profile)/ default-size-rows" "35"
  gsettings-set "com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/$(tilix-default-profile)/ allow-bold" "false"
  gsettings-set "com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/$(tilix-default-profile)/ scrollback-unlimited" "true"
  gsettings-set "com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/$(tilix-default-profile)/ use-system-font" "false"
  gsettings-set "com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/$(tilix-default-profile)/ font" 'Fira Code 13'
fi
################################################################################
