#!/usr/bin/env bash

#Helper function
gsettings-set() {
  setting=$1
  value=$2
  local old_value=$(gsettings get $1)
  gsettings set $1 "$2"
  echo "$setting: ${old_value} -> $(gsettings get $1)"
}

#Terminal colors
C_FG="#E0E0E0"
C_BG="#212121"
C_HFG="#FF4081"
C_HBG="#000A12"
C_PAL="['#424242', '#E53834', '#43A047', '#FDD835', '#1D87E5', '#8D24AA', '#00897A', '#90A4AE', '#757575', '#E57272', '#81C784', '#FFF176', '#64B5F6', '#BA68C8', '#4DB6AC', '#CFD8DC']"


################### Gnome Shell and WM #########################################
echo ""
echo "----- Gnome Settings --------"
gsettings-set "org.gnome.shell.keybindings focus-active-notification" "[]"
gsettings-set "org.gnome.shell.keybindings toggle-message-tray" "[]"

gsettings-set "org.gnome.desktop.wm.keybindings maximize-vertically" "['<Shift><Alt>r']"
gsettings-set "org.gnome.desktop.wm.keybindings switch-applications" "['<Super>Tab']"
gsettings-set "org.gnome.desktop.wm.keybindings switch-windows" "['<Alt>Tab']"
gsettings-set "org.gnome.desktop.wm.preferences action-middle-click-titlebar"  'toggle-maximize-vertically'
gsettings-set "org.gnome.desktop.wm.preferences button-layout" "appmenu:minimize,maximize,close"

gsettings-set "org.gnome.desktop.interface font-name" "IBM Plex Sans 11"
gsettings-set "org.gnome.desktop.interface document-font-name" "IBM Plex Sans 11"
gsettings-set "org.gnome.desktop.interface monospace-font-name" "Hack 12"
gsettings-set "org.gnome.desktop.wm.preferences titlebar-font" "IBM Plex Sans Medium 11"

gsettings-set "org.gnome.desktop.interface cursor-size" "32"
echo "-----------------------------------"
################################################################################


################### Gnome Terminal #############################################
echo ""
echo "----- Gnome Terminal Settings -----"
gdp=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \')
default_profile_path="org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${gdp}/"
gsettings-set "org.gnome.Terminal.Legacy.Settings default-show-menubar" "false"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ copy" "<Super>c"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ paste" "<Super>v"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ new-tab" "<Super>t"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ close-tab" "<Super>w"
gsettings-set "org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/ reset-and-clear" "<Super>r"
gsettings-set "${default_profile_path} allow-bold" "false"
gsettings-set "${default_profile_path} text-blink-mode" "never"
gsettings-set "${default_profile_path} default-size-columns" "120"
gsettings-set "${default_profile_path} default-size-rows" "30"
gsettings-set "${default_profile_path} scrollback-unlimited" "true"
gsettings-set "${default_profile_path} use-system-font" "false"
gsettings-set "${default_profile_path} font" 'DejaVu Sans Mono 10'
gsettings-set "${default_profile_path} cursor-shape" "ibeam"
gsettings-set "${default_profile_path} audible-bell" "false"
gsettings-set "${default_profile_path} use-theme-colors" "false"
gsettings-set "${default_profile_path} highlight-colors-set" "true"
gsettings-set "${default_profile_path} foreground-color" "$C_FG"
gsettings-set "${default_profile_path} background-color" "$C_BG"
gsettings-set "${default_profile_path} highlight-foreground-color" "$C_HFG"
gsettings-set "${default_profile_path} highlight-background-color" "$C_HBG"
gsettings-set "${default_profile_path} palette" "$C_PAL"
echo "-----------------------------------"
################################################################################


################### Tilix ######################################################
if [[ -x "$(command -v tilix)" ]]; then
  echo ""
  echo "----- Tilix Settings --------------"
  tdp=$(gsettings get com.gexperts.Tilix.ProfilesList default | tr -d \')
  default_profile_path="com.gexperts.Tilix.Profile:/com/gexperts/Tilix/profiles/${tdp}/"
  gsettings-set "com.gexperts.Tilix.Settings use-overlay-scrollbar" "false"
  gsettings-set "com.gexperts.Tilix.Settings use-tabs" "true"
  gsettings-set "com.gexperts.Tilix.Settings unsafe-paste-alert" "false"
  gsettings-set "com.gexperts.Tilix.Settings terminal-title-style" "small"
  gsettings-set "com.gexperts.Tilix.Keybindings terminal-copy" "<Super>c"
  gsettings-set "com.gexperts.Tilix.Keybindings terminal-paste" "<Super>v"
  gsettings-set "com.gexperts.Tilix.Keybindings app-new-session" "<Super>t"
  gsettings-set "com.gexperts.Tilix.Keybindings session-close" "<Super>w"
  gsettings-set "com.gexperts.Tilix.Keybindings terminal-reset-and-clear" "<Super>r"
  gsettings-set "${default_profile_path} allow-bold" "false"
  gsettings-set "${default_profile_path} text-blink-mode" "never"
  gsettings-set "${default_profile_path} default-size-columns" "120"
  gsettings-set "${default_profile_path} default-size-rows" "35"
  gsettings-set "${default_profile_path} scrollback-unlimited" "true"
  gsettings-set "${default_profile_path} use-system-font" "false"
  gsettings-set "${default_profile_path} font" 'Hack 13'
  gsettings-set "${default_profile_path} cursor-shape" "ibeam"
  gsettings-set "${default_profile_path} terminal-bell" "none"
  gsettings-set "${default_profile_path} use-theme-colors" "false"
  gsettings-set "${default_profile_path} highlight-colors-set" "true"
  gsettings-set "${default_profile_path} foreground-color" "$C_FG"
  gsettings-set "${default_profile_path} background-color" "$C_BG"
  gsettings-set "${default_profile_path} highlight-foreground-color" "$C_HFG"
  gsettings-set "${default_profile_path} highlight-background-color" "$C_HBG"
  gsettings-set "${default_profile_path} palette" "$C_PAL"

  echo "-----------------------------------"
fi
################################################################################
