#!/usr/bin/env bash

mkdir -p ~/.config/htop

TARGET=~/.config/htop/htoprc


[[ -f $TARGET ]] && [[ ! -h $TARGET ]] && mv $TARGET{,.backup}
[[ -h $TARGET ]] && echo "Link for htoprc already exists" && exit 0
ln -s $DOTFILES_PATH/config/htop/desktop_htoprc $TARGET
