#!/usr/bin/env bash

source ./lib/__tools.bash
source ./lib/__terminal-colors.bash


./lib/gnome-shell-settings.bash
./lib/nautilus-settings.bash
./lib/gnome-terminal.bash __terminal-colors-dracula.bash

if [[ -x "$(command -v tilix)" ]]; then
  ./lib/tilix-settings.bash __terminal-colors.bash
fi
