#!/usr/bin/env bash

source ./lib/__tools.bash

echo "============================= Gome Shell ==========================="
./lib/gnome-shell-settings.bash set
echo "===================================================================="

echo "============================= Nautilus ============================="
./lib/nautilus-settings.bash set
echo "===================================================================="

echo "============================= Gnome Terminal ======================="
./lib/gnome-terminal.bash set ./lib/__terminal-colors.bash
echo "===================================================================="

if [[ -x "$(command -v tilix)" ]]; then
  echo "============================= Tilix ================================"
  ./lib/tilix-settings.bash set ./lib/__terminal-colors.bash
  echo "===================================================================="
fi
