#!/usr/bin/env sh

#Requirements:
#  $1
#  $2
#  $3
#  $4

D_USER=${1:-user1}
D_USER_ID=${2:-1000}
D_GROUP=${3:-user1}
D_GROUP_ID=${4:-1000}
D_USER_HOME_DIR=${5:-/home/user1}

groupadd -g "$D_GROUP_ID" "$D_GROUP" || true

FGN=$(getent group $D_GROUP_ID | cut -d: -f1)

echo "Creating user  $D_USER ($D_USER_ID)"
echo "         group $D_GROUP ($D_GROUP_ID)"
echo "         home  $D_USER_HOME_DIR"
echo "         group to use $FGN"

useradd \
  --create-home \
  --home-dir "$D_USER_HOME_DIR" \
  --gid "$FGN" \
  --password 1234 \
  --shell /usr/bin/bash \
  --uid "$D_USER_ID" "$D_USER"

echo "$D_USER ALL=(ALL) ALL" > /etc/sudoers.d/$D_USER
echo "${D_USER}:1234" | chpasswd
