#!/usr/bin/env bash

# https://ghostty.org/docs/config
# https://ghostty.org/docs/config/reference#theme

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# config path
CONF_PATH="${HOME}/.config/ghostty"
if [[ $(uname) == "Darwin" ]]; then
  CONF_PATH="${HOME}/Library/Application Support/com.mitchellh.ghostty"
fi
mkdir -p "${CONF_PATH}"

# themes path
# $XDG_CONFIG_DIR/ghostty/themes or ~/.config/ghostty/themes.
THEMES_PATH="${HOME}/.config/ghostty/themes"
mkdir -p "${THEMES_PATH}"

# Install
lnx "${SRC}/config" "${CONF_PATH}/config"
lnx "${SRC}/github_dimmed" "${THEMES_PATH}/github_dimmed"
