#!/usr/bin/env bash

sudo ln -s /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d/
sudo ln -s /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d/
sudo ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/

# gsettings get org.gnome.desktop.interface font-antialiasing
# gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'

# gsettings get org.gnome.desktop.interface font-rgba-order
# gsettings set org.gnome.desktop.interface font-rgba-order 'rgb'

# gsettings get org.gnome.desktop.interface font-hinting
# gsettings set org.gnome.desktop.interface font-hinting 'slight'
