#!/usr/bin/env bash

set -e

sudo dnf remove -y inkscape
sudo dnf install -y inkscape-0.92.4-8.fc31
(
cd $HOME/gitrepos/plata-theme
rm -rf *
git checkout -- .
)
GS-update-plata
sudo dnf remove -y inkscape
