#!/usr/bin/env bash

sudo dnf -y groupinstall multimedia

sudo dnf -y install \
    amrnb \
    amrwb \
    clang-libs \
    faac \
    faad2 \
    faad2-libs \
    ffmpeg-libs \
    flac \
    fribidi \
    gstreamer-ffmpeg \
    gstreamer-plugins-bad \
    gstreamer-plugins-bad-nonfree \
    gstreamer-plugins-espeak \
    gstreamer-plugins-ugly \
    gstreamer1-libav \
    gstreamer1-plugins-bad-freeworld \
    gstreamer1-plugins-ugly \
    hwloc-libs \
    lame \
    libass \
    libclc \
    libdca \
    libde265 \
    libebml \
    libfc14audiodecoder \
    libmad \
    libmatroska \
    libmfx \
    libmimic \
    libmms \
    libmpeg2 \
    libofa \
    librtmp \
    libva \
    mjpegtools-libs \
    ocl-icd \
    opencl-filesystem \
    opencore-amr \
    schroedinger \
    vid.stab \
    vo-amrwbenc \
    x264 \
    x264-libs \
    x265 \
    x265-libs \
    xvidcore \
    libldac

# sudo dnf install celluloid.x86_64
# sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
# sudo dnf install mesa-vdpau-drivers-freeworld
