#!/usr/bin/env bash

# https://rpmfusion.org/Howto/Multimedia

# sudo dnf swap ffmpeg-free ffmpeg --allowerasing
# sudo dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
# sudo dnf install intel-media-driver

## bluetooth aptx and ldac
sudo dnf -y install \
  libldac \
  pipewire-codec-aptx \
  libfreeaptx \
  libfreeaptx-tools

# codecs
sudo dnf -y install \
  lame \
  faad2 \
  faad2-libs \
  flac \
  gstreamer-ffmpeg \
  gstreamer-plugins-bad \
  gstreamer-plugins-bad-nonfree \
  gstreamer-plugins-espeak \
  gstreamer-plugins-ugly \
  gstreamer1-libav \
  gstreamer1-plugins-bad-freeworld \
  gstreamer1-plugins-ugly \
  libavcodec-freeworld \
  libavdevice \
  libde265 \
  librtmp \
  libva-intel-driver \
  mjpegtools-libs \
  svt-hevc-libs \
  libass \
  libclc \
  libdca \
  libde265 \
  libebml \
  libfc14audiodecoder \
  libmad \
  libmatroska \
  libmfx \
  libmimic \
  libmms \
  libmpeg2 \
  libofa \
  librtmp \
  libva \
  x264 \
  x264-libs \
  x265 \
  x265-libs

# sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
