#!/usr/bin/env bash

sudo systemctl stop firewalld.service
sudo systemctl disable firewalld.service

sudo dnf install \
  git git-delta sqlite gcc gcc-c++ strace gdb cmake automake make binutils-devel glibc-devel glibc-static \
  jq curl wget redhat-lsb-core htop vim vim-common vim-enhanced nano \
  ack ripgrep

sudo dnf install \
  meld gitg gitk \
  gnome-tweak-tool gnome-extensions-app gnome-usage \
  gtk-murrine-engine gtk-unico-engine gtk2-engines pavucontrol \
  atop iftop iotop nmon nvtop procps-ng bat duf fd-find fzf

sudo dnf install \
  pavucontrol gnome-shell-extension-user-theme chrome-gnome-shell

sudo dnf groupinstall "Development Tools"
sudo dnf install @development-tools
#sudo dnf install @development-libs
#sudo dnf install gnome-builder
#sudo dnf install @gnome-software-development

sudo dnf install \
  kernel-devel \
  kernel-headers \
  kernel-modules \
  kernel-modules-extra

#sudo dnf install akmods akmod-wl broadcom-wl

#sudo dnf grouperase "Container Management"

#sudo dnf -y groupinstall virtualization

sudo dnf -y install cabextract lzip p7zip p7zip-plugins unrar

# sudo dnf install igt-gpu-tools # intel_gpu_top
