#!/usr/bin/env bash

gsettings set org.gnome.software download-updates false

sudo systemctl stop firewalld.service
sudo systemctl disable firewalld.service

sudo dnf install \
  git gitg meld sqlite gcc gcc-c++ cmake automake make \
  jq curl wget redhat-lsb-core htop vim vim-common vim-enhanced nano ack \
  gnome-tweak-tool gnome-shell-extension-user-theme chrome-gnome-shell \
  gtk-murrine-engine gtk-unico-engine gtk2-engines

sudo dnf groupinstall "Development Tools"
sudo dnf install @development-tools
#sudo dnf install @development-libs
#sudo dnf install gnome-builder
#sudo dnf install @gnome-software-development

sudo dnf install \
  java-1.8.0-openjdk \
  java-1.8.0-openjdk-devel \
  java-1.8.0-openjdk-headless \
  java-1.8.0-openjdk-javadoc \
  java-1.8.0-openjdk-javadoc-zip \
  java-1.8.0-openjdk-src

sudo dnf install \
  java-11-openjdk \
  java-11-openjdk-devel \
  java-11-openjdk-headless \
  java-11-openjdk-javadoc \
  java-11-openjdk-javadoc-zip \
  java-11-openjdk-jmods \
  java-11-openjdk-src

sudo dnf install \
  kernel-devel \
  kernel-headers \
  kernel-modules \
  kernel-modules-extra

#sudo dnf install akmods akmod-wl broadcom-wl
