#!/usr/bin/env bash

GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
echo " -> Current theme $GTK_THEME"
if [[ $GTK_THEME == *Materia* ]]; then
  (
  echo " -> To use: /usr/share/themes/${GTK_THEME}/gnome-shell/gnome-shell-theme.gresource.xml"
  cd /usr/share/themes/${GTK_THEME}/gnome-shell
  sudo glib-compile-resources --target=/usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme.gresource.xml
  )
fi
