#!/usr/bin/env bash

set -e

DOWNLOAD_DEST_FILE='/tmp/telegram.tar.xz'
rm -rf $DOWNLOAD_DEST_FILE
DESKTOP_FILE="$HOME/.local/share/applications/telegramdesktop.desktop"

__LINK=$(curl -sSfL https://api.github.com/repos/telegramdesktop/tdesktop/releases/latest | jq '.assets[] | select(.name | test("tsetup\\.[\\d|.]*\\.tar.xz")) | .browser_download_url' --raw-output)
curl --fail --location $__LINK -o $DOWNLOAD_DEST_FILE
mkdir -p ~/Applications/
tar xf $DOWNLOAD_DEST_FILE -C ~/Applications/
rm $DOWNLOAD_DEST_FILE

cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
X-GNOME-UsesNotifications=true
EOL

echo "TryExec=${HOME}/Applications/Telegram/Telegram" >> $DESKTOP_FILE
echo "Exec=${HOME}/Applications/Telegram/Telegram -- %u" >> $DESKTOP_FILE
