#!/usr/bin/env bash

case "$(what-os)" in
  "Fedora")
    sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    sudo dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    sudo dnf install --assumeyes sublime-text
    ;;
  "Ubuntu"|"Debian"|"LinuxMint"|"Pop")
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
    sudo apt install -y apt-transport-https
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    sudo apt update
    sudo apt install -y sublime-text
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac
