#!/usr/bin/env bash

DOWNLOAD_DEST_FILE='/tmp/telegram.tar.xz'
#TELE_EXECUTABLE="$HOME/Applications/Telegram/start_telegram"
DESKTOP_FILE="$HOME/.local/share/applications/telegramdesktop.desktop"

wget 'https://telegram.org/dl/desktop/linux' -O $DOWNLOAD_DEST_FILE
mkdir -p ~/Applications/
tar xf $DOWNLOAD_DEST_FILE -C ~/Applications/
rm $DOWNLOAD_DEST_FILE

#echo "FONTCONFIG_FILE=/etc/fonts/ $HOME/Applications/Telegram/Telegram -- %u" > $TELE_EXECUTABLE
#chmod +x $TELE_EXECUTABLE

cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=/home/kostas/Applications/Telegram/Telegram
Exec=/home/kostas/Applications/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
X-GNOME-UsesNotifications=true
EOL

#echo "TryExec=$TELE_EXECUTABLE" >> $DESKTOP_FILE
#echo "Exec=$TELE_EXECUTABLE -- %u" >> $DESKTOP_FILE
