#!/usr/bin/env bash
set -e

whatos() {
  if [[ -f /etc/os-release ]]; then
    (
    source /etc/os-release
    echo "${NAME}"
    )
    return
  fi

  if command -v lsb_release >/dev/null 2>&1; then
    lsb_release -is
    return
  fi

  echo ""
}

case "$(whatos)" in
  "Fedora"|"Fedora Linux")
    sudo dnf install -y dnf-plugins-core
    sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    sudo dnf -y install terraform
    ;;
  "Ubuntu"|"Debian"|"LinuxMint"|"Pop")
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform
    ;;
  *)
    echo "this script does not have packages for this release"
    exit 1
    ;;
esac

echo -e "\e[1;32mDone\e[0m\n"

terraform -install-autocomplete
