#!/usr/bin/env bash

set -e

__remote_version() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.name'
}
export -f __remote_version

__local_version() {
  local BIN_DIR="${1:-/usr/local/bin}"
  [[ -f "${BIN_DIR}/starship" ]] && echo "v$("${BIN_DIR}/starship" --version | grep 'starship ' | awk '{ print $2 }')"
}
export -f __local_version

__get_dl_url() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.assets[] | select(.name | test("^starship-x86_64-unknown-linux-gnu.tar.gz$")) | .browser_download_url'
}
export -f __get_dl_url

__install_exec() {
  local BIN_DIR="${1}"
  local DOWNLOADED_FULL_PATH="${2}"
  local TMP_DIR
  TMP_DIR="$(dirname "${DOWNLOADED_FULL_PATH}")"
  tar -xzf "${DOWNLOADED_FULL_PATH}" --directory "${TMP_DIR}"
  sudo cp "${TMP_DIR}"/starship "${BIN_DIR}"/starship
}
export -f __install_exec


install-from-github \
  --name                 "starship" \
  --repo                 "starship/starship" \
  --fn-remote-version    "__remote_version" \
  --fn-local-version     "__local_version" \
  --fn-get-download-link "__get_dl_url" \
  --download-to-file     "downloaded.tar.gz" \
  --fn-install           "__install_exec" \
  --destination          "/usr/local/bin" \
  "${@}"
