#!/usr/bin/env bash

URL=""
case "$(what-pm)" in
  "dnf")
    URL="https://zoom.us/client/latest/zoom_x86_64.rpm"
    ;;
  "apt")
    URL="https://zoom.us/client/latest/zoom_amd64.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install-remote-package $URL
