#!/usr/bin/env bash

sudo test
os_name=$(lsb_release -is)
URL=""
case "$os_name" in
  "Fedora")
    URL="https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
    ;;
  "Ubuntu"|"Debian"|"LinuxMint")
    URL="https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install_remote_package $URL
