#!/usr/bin/env bash

case "$(what-pm)" in
  "dnf")
    sudo dnf -y install zlib.i686 ncurses-libs.i686 bzip2-libs.i686
    ;;
  "apt")
    sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac


URL=$(curl https://developer.android.com/studio/ -s | egrep "<a href=\"[^\"]*-linux.zip\"" | egrep -oh "https://[^\"]*-linux.zip")

wget $URL -O /tmp/android-studio.zip

mkdir -p ~/Android
unzip /tmp/android-studio.zip -d ~/Android/

rm /tmp/android-studio.zip

DESKTOP_FILE="$HOME/.local/share/applications/jetbrains-studio.desktop"
cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-studio
EOL
echo "Exec=\"$HOME/Android/android-studio/bin/studio.sh\" %f" >> $DESKTOP_FILE
echo "Icon=$HOME/Android/android-studio/bin/studio.png" >> $DESKTOP_FILE
