#!/usr/bin/env bash

DOWNLOAD_DEST_FILE='/tmp/telegram.tar.xz'
rm -rf $DOWNLOAD_DEST_FILE
DESKTOP_FILE="$HOME/.local/share/applications/telegramdesktop.desktop"

__LINK=$(curl -sSfL https://api.github.com/repos/telegramdesktop/tdesktop/releases/latest | jq '.assets[] | select(.name | test("tsetup\\.[\\d|.]*\\.tar.xz")) | .browser_download_url' --raw-output)
curl --silent --show-error --fail --location $__LINK -o $DOWNLOAD_DEST_FILE
mkdir -p ~/Applications/
tar xf $DOWNLOAD_DEST_FILE -C ~/Applications/
rm $DOWNLOAD_DEST_FILE

echo "[Desktop Entry]
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
TryExec=${HOME}/Applications/Telegram/Telegram
Exec=${HOME}/Applications/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=Quit;
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action Quit]
Exec=${HOME}/Applications/Telegram/Telegram -quit
Name=Quit Telegram
Icon=application-exit
" > $DESKTOP_FILE
