#!/usr/bin/env bash

__os_name() {(
  if [[ -f /etc/os-release ]]; then
    source /etc/os-release
    echo "${NAME}"
    exit 0
  fi

  if command -v lsb_release >/dev/null 2>&1; then
    lsb_release -is
    exit 0
  fi

  echo "no available os name"
  exit 1
)}

__get_latest_version() {
  curl --fail --silent --show-error --location https://api.github.com/repos/dbeaver/dbeaver/releases/latest | jq -r '.tag_name'
}

__get_local_release() {(
  [[ ! -e /usr/share/dbeaver/.eclipseproduct ]] && echo "" && return
  cat /usr/share/dbeaver/.eclipseproduct | grep --extended-regexp "^version" | sed "s/version=//"
)}

if [[  "$(__get_local_release)" == "$(__get_latest_version)" ]]; then
  echo "dbeaver is updated to $remote_version";
  exit 0
fi

URL=""
case "$(__os_name)" in
  "Fedora")
    URL="https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm"
    ;;
  "Ubuntu"|"Debian"|"LinuxMint"|"Pop")
    URL="https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install-remote-package $URL

unset URL
