#!/usr/bin/env bash

__install_zips() {
  unzip -q "${1}.zip"
}

__install_targzs() {
  tar --strip-components=1 --extract --gzip --file="${1}.tar.gz"
}

# $1 = Github release json
# $2 = Font name
# $3 = Temp dir to download
# $4 = Compressed file extension without dot ("zip" or "tar.gz")
# $5 = Uncompress function
__install_bibata_cursors_() {
  local JSON_TEXT=$1
  local NAME=$2
  local TMP_DIR=$3
  local EXT=$4
  local UNCOMPRESS=$5

  local URL=$(echo $JSON_TEXT | jq ".assets[] | select(.name == \"${NAME}.${EXT}\") | .browser_download_url" --raw-output)
  echo ""
  echo -e "Installing \e[1;33m${NAME}\e[0m"
  (
  set -e
  mkdir -p $TMP_DIR/$NAME
  cd $TMP_DIR/$NAME
  echo -e "    Downloading \e[1;34m${URL}\e[0m"
  curl --fail --silent --show-error --location $URL --output "${NAME}.${EXT}"
  echo -e "    Exctracting \e[1;34m${NAME}.${EXT}\e[0m"
  ${UNCOMPRESS} "${NAME}"
  rm "${NAME}.${EXT}"
  [[ -d "${HOME}/.icons/${NAME}" ]] && rm -rf "${HOME}/.icons/${NAME}"
  echo -e "    Move to     \e[1;34m~/.icons/${NAME}\e[0m"
  mv $TMP_DIR/$NAME $HOME/.icons
  )
}


# $1 = Github release json
# $2 = Font name
# $3 = Temp dir to download
__install_bibata_cursors_zips() {
  __install_bibata_cursors_ "$1" "$2" "$3" "zip" "__install_zips"
}

__install_bibata_cursors_targzs() {
  __install_bibata_cursors_ "$1" "$2" "$3" "tar.gz" "__install_targzs"
}

# check if jq already exists
if ! [ -x "$(command -v jq)" ]; then
    echo 'Error: jq is not installed. Please install it' >&2
    exit 1
fi

mkdir -p $HOME/.icons
rm -rf $HOME/.icons/Bibata_*
TMP_DIR='/tmp/bibata_install'
rm -rf $TMP_DIR
mkdir -p $TMP_DIR

JSON_TEXT_MAIN=$(curl -s https://api.github.com/repos/ful1e5/Bibata_Cursor/releases/latest)
for NAME in 'Bibata-Modern-Amber' 'Bibata-Modern-Classic' 'Bibata-Modern-Ice' 'Bibata-Original-Amber' 'Bibata-Original-Classic' 'Bibata-Original-Ice'
do
  __install_bibata_cursors_targzs "${JSON_TEXT_MAIN}" $NAME $TMP_DIR
done

JSON_TEXT_EXTRA=$(curl -s https://api.github.com/repos/ful1e5/Bibata_Extra_Cursor/releases/latest)
for NAME in 'Bibata_Dark_Red' 'Bibata_Dodger_Blue' 'Bibata_Pink' 'Bibata_Turquoise'
do
  __install_bibata_cursors_zips "${JSON_TEXT_EXTRA}" $NAME $TMP_DIR
done

rm -rf $TMP_DIR

unset -f __install_bibata_cursors_zips
unset -f __install_bibata_cursors_targzs
unset TMP_DIR
unset JSON_TEXT_MAIN
unset JSON_TEXT_EXTRA
