#!/usr/bin/env bash

# $HOME/.docker/cli-plugins

# /usr/local/lib/docker/cli-plugins
# /usr/local/libexec/docker/cli-plugins

# /usr/lib/docker/cli-plugins
# /usr/libexec/docker/cli-plugins

# PLUGINS_DIR="${HOME}/.docker/cli-plugins/"
# mkdir -p "${PLUGINS_DIR}"
PLUGINS_DIR="/usr/local/lib/docker/cli-plugins"
sudo mkdir -p "${PLUGINS_DIR}"

__remote_version() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.name'
}
export -f __remote_version

__local_version() {
  local BIN_DIR="${1:-/usr/local/bin}"
  docker compose version | awk '{ print $4 }'
}
export -f __local_version

__get_dl_url() {
  local JS_BODY="${1}"
  local ENDSWITH
  ENDSWITH=$(echo "$(uname -s)-$(uname -m)" | tr '[:upper:]' '[:lower:]')
  case "${ENDSWITH}" in
    "linux-x86_64")
      ENDSWITH="linux-x86_64"
      ;;
    "linux-aarch64")
      ENDSWITH="linux-aarch64"
      ;;
    "darwin-x86_64")
      ENDSWITH="darwin-x86_64"
      ;;
    "darwin-arm64")
      ENDSWITH="darwin-aarch64"
      ;;
  esac
  echo "${JS_BODY}" | jq -r ".assets[] | select(.name | endswith(\"${ENDSWITH}\")) | .browser_download_url"
}
export -f __get_dl_url

__install_exec() {
  local BIN_DIR="${1}"
  local DOWNLOADED_FULL_PATH="${2}"

  # cp "${DOWNLOADED_FULL_PATH}" "${BIN_DIR}"/docker-compose
  # chmod +x "${BIN_DIR}"/docker-compose

  sudo install -D --owner=root --group=root --mode=0755 "${DOWNLOADED_FULL_PATH}" "${BIN_DIR}/docker-compose"
  #  -D     create all leading components of DEST except the last, or all components  of  --target-directory,  then copy SOURCE to DEST
}
export -f __install_exec

install-from-github \
  --name "docker-compose" \
  --repo "docker/compose" \
  --fn-remote-version "__remote_version" \
  --fn-local-version "__local_version" \
  --fn-get-download-link "__get_dl_url" \
  --download-to-file "docker-compose" \
  --fn-install "__install_exec" \
  --destination "${PLUGINS_DIR}" \
  "${@}"
