#!/usr/bin/env bash

URL_RELEASE="https://data.services.jetbrains.com/products/releases?code=WS&latest=true"
URL=$(wget $URL_RELEASE -q -O - | jq '.WS[0].downloads.linux.link' -r)
DOWNLOADED_FILE="/tmp/webstorm.tar.gz"
INSTALLATION_DIR="$HOME/Applications/webstorm"
DESKTOP_FILE="$HOME/.local/share/applications/jetbrains-webstorm.desktop"

wget $URL -O $DOWNLOADED_FILE
mkdir -p $INSTALLATION_DIR
tar zxf $DOWNLOADED_FILE --strip-components=1 -C $INSTALLATION_DIR
rm $DOWNLOADED_FILE
cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Type=Application
Name=WebStorm
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-webstorm
EOL
echo "Exec=\"$INSTALLATION_DIR/bin/webstorm.sh\" %f" >> $DESKTOP_FILE
echo "Icon=$INSTALLATION_DIR/bin/webstorm.png" >> $DESKTOP_FILE
