#!/usr/bin/env bash

case "$(what-pm)" in
  "dnf")
    sudo dnf install lpf-spotify-client
    sudo usermod -aG pkg-build ksta
    ;;
  "apt")
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
    sudo apt update
    sudo apt install -y spotify-client
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac
