#!/usr/bin/env bash

# $1: version e.g. 1.12.7
# https://storage.googleapis.com/golang/go1.12.7.linux-amd64.tar.gz
curl -L --fail https://storage.googleapis.com/golang/go$1.linux-amd64.tar.gz > /tmp/go$1.linux-amd64.tar.gz
if [ -d /usr/local/go ]; then sudo rm -rf /usr/local/go; fi
sudo tar -C /usr/local -xzf /tmp/go$1.linux-amd64.tar.gz
rm /tmp/go$1.linux-amd64.tar.gz
