#!/usr/bin/env bash

__remote_version() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.tag_name'
}
export -f __remote_version

__local_version() {
  #local BIN_DIR="${1:-/usr/local/bin}" # not used in this case
  [[ ! -e /usr/share/dbeaver-ce/.eclipseproduct ]] && echo "" && return
  cat /usr/share/dbeaver-ce/.eclipseproduct | grep --extended-regexp "^version" | sed "s/version=//"
}
export -f __local_version

__get_dl_url() {
  local JS_BODY="${1}"

  case "$(what-pm)" in
    "dnf")
      echo "${JS_BODY}" | jq -r '.assets[] | select(.name | test("\\.x86_64.rpm$")) | .browser_download_url'
      ;;
    "apt")
      echo "${JS_BODY}" | jq -r '.assets[] | select(.name | test("_amd64.deb$")) | .browser_download_url'
      ;;
    *)
      echo ""
      ;;
  esac
}
export -f __get_dl_url

__install_exec() {
  #local BIN_DIR="${1}" # not used in this case
  local DOWNLOADED_FULL_PATH="${2}"
  local TMP_DIR
  TMP_DIR="$(dirname "${DOWNLOADED_FULL_PATH}")"

  case "$(what-pm)" in
    "dnf")
      sudo dnf -y install "${DOWNLOADED_FULL_PATH}"
      ;;
    "apt")
      sudo chown -R _apt "${TMP_DIR}"
      sudo apt -y install "${DOWNLOADED_FULL_PATH}"
      ;;
    *)
      return 1
      ;;
  esac
}
export -f __install_exec

install-from-github \
  --name "dbeaver" \
  --repo "dbeaver/dbeaver" \
  --fn-remote-version "__remote_version" \
  --fn-local-version "__local_version" \
  --fn-get-download-link "__get_dl_url" \
  --download-to-file "" \
  --fn-install "__install_exec" \
  --destination "/usr/local/bin" \
  "${@}"
