#!/usr/bin/env bash

URL=""
case "$(what-pm)" in
  "dnf")
    URL="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    ;;
  "apt")
    URL="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    exit 1
    ;;
esac

install-remote-package "${URL}"
