#!/usr/bin/env bash

set -euo pipefail

VER="${1:-}" # first argument is the version number e.g. 1.19

if [ -z "${VER}" ]; then
  VER=$(curl -L -s https://dl.k8s.io/release/stable.txt)
fi

if [[ ${VER} != v* ]]; then
  VER="v${VER}"
fi

__LOCAL_VER=""
if command -v kubectl &>/dev/null; then
  __LOCAL_VER=$(kubectl version --client | grep 'Client Version' | sed 's/Client Version: //')
fi

if [[ ${VER} == "${__LOCAL_VER}" ]]; then
  echo -e "kubectl is already in version \e[1;34m${__LOCAL_VER}\e[0m"
  exit 0
fi

printf "Installing kubectl \e[1;34m%s\e[0m \n" "${VER}"

rm -rf /tmp/kubectl_install || true
mkdir -p /tmp/kubectl_install

curl --fail --show-error --location \
  "https://dl.k8s.io/release/${VER}/bin/linux/amd64/kubectl" \
  --output /tmp/kubectl_install/kubectl

sudo install -o root -g root -m 0755 /tmp/kubectl_install/kubectl /usr/local/bin/kubectl

rm -rf /tmp/kubectl_install || true
