#!/usr/bin/env bash
(
set -e
# $1: version e.g. 1.17.11
# https://storage.googleapis.com/golang/go1.17.11.linux-amd64.tar.gz
[[ -z $1  ]] && echo "Error: No go version specified" && exit 1

command -v go &> /dev/null && [[ ! -d /usr/local/go ]] && echo -e "\e[32mGo has been installed in a different whay and not in path /usr/local/go.\e[0m Aborting..." && exit 1


DR=$(mktemp --directory --tmpdir golang_XXXXXXX)
cd $DR
echo -e "Downloading \e[34mhttps://storage.googleapis.com/golang/go$1.linux-amd64.tar.gz\e[0m in \e[34m${PWD}\e[0m"
curl --fail --silent --show-error --location https://storage.googleapis.com/golang/go$1.linux-amd64.tar.gz > go.linux-amd64.tar.gz
[[ -d /usr/local/go ]] && echo -e "\e[37mDelete previous go installation (\e[0m$(go version)\e[37m)\e[0m" && sudo rm -rf /usr/local/go
echo -e "Installing go \e[34m$1\e[0m"
sudo tar -C /usr/local -xzf go.linux-amd64.tar.gz
cd /

sudo rm -rf $DR
echo -e "\e[1;32mDone\e[0m"
)
