#!/usr/bin/env bash

__remote_version() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.name' | cut --characters='2-' # cut -c 2-    # v0.22.1 -> 0.22.1
}
export -f __remote_version

__local_version() {
  local BIN_DIR="${1:-/usr/local/bin}"
  [[ -f "${BIN_DIR}"/bat ]] && "${BIN_DIR}"/bat --version | cut --delimiter=' ' --fields=2 # cut -d' ' -f2
}
export -f __local_version

__get_dl_url() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.assets[] | select(.name | endswith("-x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url'
}
export -f __get_dl_url

__install_exec() {
  local BIN_DIR="${1}"
  local DOWNLOADED_FULL_PATH="${2}"
  local TMP_DIR
  TMP_DIR="$(dirname "${DOWNLOADED_FULL_PATH}")"
  tar -xzf "${DOWNLOADED_FULL_PATH}" --directory "${TMP_DIR}" --strip-components=1

  #install binary
  sudo cp "${TMP_DIR}"/bat "${BIN_DIR}"/bat

  # install bash completion
  if [[ -d "${HOME}"/.bashrc.d/ ]]; then
    cat "${TMP_DIR}"/autocomplete/bat.bash > "${HOME}"/.bashrc.d/bat-completion.bash
  fi
}
export -f __install_exec


install-from-github  \
  --name                 "bat" \
  --repo                 "sharkdp/bat" \
  --fn-remote-version    "__remote_version" \
  --fn-local-version     "__local_version" \
  --fn-get-download-link "__get_dl_url" \
  --download-to-file     "downloaded.tar.gz" \
  --fn-install           "__install_exec" \
  --destination          "/usr/local/bin" \
  "${@}"
