#!/usr/bin/env bash
set -e

whatos() {
  if [[ -f /etc/os-release ]]; then
    (
    source /etc/os-release
    echo "${NAME}"
    )
    return
  fi

  if command -v lsb_release >/dev/null 2>&1; then
    lsb_release -is
    return
  fi

  echo ""
}

case "$(whatos)" in
  "Fedora"|"Fedora Linux")
    #sudo dnf remove docker \
    #                docker-client \
    #                docker-client-latest \
    #                docker-common \
    #                docker-latest \
    #                docker-latest-logrotate \
    #                docker-logrotate \
    #                docker-selinux \
    #                docker-engine-selinux \
    #                docker-engine
    sudo dnf -y install dnf-plugins-core
    sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf check-update
    sudo dnf -y install docker-ce docker-ce-cli containerd.io
    ;;
  "Ubuntu"|"Debian"|"LinuxMint"|"Pop")
    # sudo apt-get --purge --yes remove docker docker-engine docker.io containerd runc
    sudo apt-get install --assume-yes apt-transport-https ca-certificates curl gnupg lsb-release
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install --assume-yes docker-ce docker-ce-cli containerd.io
    ;;
  *)
    echo "this script does not have packages for this release"
    exit 1
    ;;
esac

echo "Installing group docker and adding the current user to it"
sudo groupadd docker || true
sudo usermod -aG docker $USER
newgrp docker

sudo systemctl enable docker.service
sudo systemctl enable containerd.service

echo -e "\e[1;32mDone\e[0m\n"

## to uninstall remove the packages and also:
# sudo rm -rf /var/lib/docker
# sudo rm -rf /var/lib/containerd
