#!/usr/bin/env bash

export CGO_ENABLED=0

__install() {
  for v in "$@"; do
    echo -e "    moving \e[0;90m${v}\e[0m -> \e[0;32m/usr/local/bin\e[0m"
  done
  sudo install --mode=755 --group=root --owner=root --target-directory=/usr/local/bin/ "$@"
  rm -rf "$@"
}

__go_install() {
  echo -e "installing \e[0;90m$@\e[0m"
  go install -a -ldflags '-s -w -extldflags "-static"' "$@"
}

# https://pkg.go.dev/golang.org/x/lint/golint?tab=versions    ## Golint is deprecated and frozen.
# __go_install 'golang.org/x/lint/golint@v0.0.0-20210508222113-6edffad5e616'

# https://pkg.go.dev/golang.org/x/tools?tab=versions
__go_install 'golang.org/x/tools/cmd/goimports@v0.1.10'
__go_install 'golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@v0.1.10'
__go_install 'golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@v0.1.10'
__install "${GOPATH}"/bin/{goimports,fieldalignment,shadow}

# https://github.com/dominikh/go-tools/releases (https://staticcheck.io/)
__go_install 'honnef.co/go/tools/cmd/staticcheck@2022.1'
__go_install 'honnef.co/go/tools/cmd/structlayout@2022.1'
__go_install 'honnef.co/go/tools/cmd/structlayout-pretty@2022.1'
__go_install 'honnef.co/go/tools/cmd/structlayout-optimize@2022.1'
__install "${GOPATH}"/bin/{staticcheck,structlayout,structlayout-pretty,structlayout-optimize}

# https://github.com/golangci/golangci-lint/releases
__go_install 'github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2'
__install "${GOPATH}"/bin/golangci-lint

# https://github.com/securego/gosec/releases
__go_install 'github.com/securego/gosec/v2/cmd/gosec@v2.11.0'
__install "${GOPATH}"/bin/gosec

# https://github.com/mvdan/gofumpt/releases
__go_install 'mvdan.cc/gofumpt@v0.3.1'
__install "${GOPATH}"/bin/gofumpt

# https://github.com/mgechev/revive/releases
__go_install 'github.com/mgechev/revive@v1.2.0'
__install "${GOPATH}"/bin/revive

################################################################
################################################################

# https://github.com/mozilla/sops/releases
__go_install 'go.mozilla.org/sops/v3/cmd/sops@v3.7.2'
__install "${GOPATH}"/bin/sops

# https://github.com/muesli/duf/releases
#__go_install 'github.com/muesli/duf@v0.8.1'
#__install "${GOPATH}"/bin/duf

# https://github.com/orijtech/structslop/tags
__go_install 'github.com/orijtech/structslop/cmd/structslop@v0.0.6'
__install "${GOPATH}"/bin/structslop

# https://github.com/xxxserxxx/gotop/releases
# __go_install 'github.com/xxxserxxx/gotop/v4/cmd/gotop@v4.1.3'
# __install "${GOPATH}"/bin/gotop

# https://github.com/bcicen/ctop/releases
# __go_install 'github.com/bcicen/ctop@v0.7.6'
