#!/usr/bin/env bash

URL=""
case "$(what-os)" in
  "Fedora")
    URL="https://zoom.us/client/latest/zoom_x86_64.rpm"
    ;;
  "Ubuntu"|"Debian"|"LinuxMint")
    URL="https://zoom.us/client/latest/zoom_amd64.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install-remote-package $URL
