#!/usr/bin/env bash

__remote_version() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.name'
}
export -f __remote_version

__local_version() {
  local BIN_DIR="${1:-/usr/local/bin}"
  [[ -f "${BIN_DIR}"/minikube ]] && "${BIN_DIR}"/minikube version --short
}
export -f __local_version

__get_dl_url() {
  local JS_BODY="${1}"
  echo "${JS_BODY}" | jq -r '.assets[] | select(.name | test("minikube-linux-amd64.tar.gz")) | .browser_download_url'
}
export -f __get_dl_url

__install_exec() {
  local BIN_DIR="${1}"
  local DOWNLOADED_FULL_PATH="${2}"
  local TMP_DIR
  TMP_DIR="$(dirname "${DOWNLOADED_FULL_PATH}")"
  tar -xzf "${DOWNLOADED_FULL_PATH}" --directory "${TMP_DIR}" --strip-components=1

  #install binary
  sudo cp "${TMP_DIR}"/minikube-linux-amd64 "${BIN_DIR}"/minikube

  # install bash completion
  if [[ -d "${HOME}"/.bashrc.d/ ]]; then
    "${BIN_DIR}"/minikube completion bash >"${HOME}"/.bashrc.d/minikube-completion.bash
  fi
}
export -f __install_exec

# #if command -v minikube 1>/dev/null 2>&1; then
# if [[ -x /usr/local/bin/minikube ]]; then
#   source <(minikube completion bash)
# fi

install-from-github \
  --name "minikube" \
  --repo "kubernetes/minikube" \
  --fn-remote-version "__remote_version" \
  --fn-local-version "__local_version" \
  --fn-get-download-link "__get_dl_url" \
  --download-to-file "downloaded.tar.gz" \
  --fn-install "__install_exec" \
  --destination "/usr/local/bin" \
  "${@}"
