#!/usr/bin/env bash

# To upgrade run with --update
tmp_dir="$(mktemp --directory)"
cd $tmp_dir || exit 1
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install "$@"
cd ~ || exit 1
rm -rf $tmp_dir
