#!/usr/bin/env bash

sudo test
os_name=$(lsb_release -is)
case "$os_name" in
  "Fedora")
    sudo dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo
    sudo dnf -y install spotify-client
    ;;
  "Ubuntu"|"Debian"|"LinuxMint")
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0DF731E45CE24F27EEEB1450EFDC8610341D9410
    echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
    sudo apt update
    sudo apt install -y spotify-client
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac
