#!/usr/bin/env bash

URL=""
case "$(what-os)" in
  "Fedora")
    URL='https://go.skype.com/skypeforlinux-64.rpm'
    ;;
  "Ubuntu"|"Debian"|"LinuxMint"|"Pop")
    URL='https://go.skype.com/skypeforlinux-64.deb'
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install-remote-package $URL
