#!/usr/bin/env bash

sudo test
os_name=$(lsb_release -is)
case "$os_name" in
  "Fedora")
    echo "installing plata requirements..."
    sudo dnf install -y \
      gtk2-engines gtk-murrine-engine gdk-pixbuf2 \
      autoconf automake inkscape gdk-pixbuf2-devel glib2-devel \
      libxml2 pkgconfig sassc parallel
    ;;
  "Ubuntu"|"LinuxMint")
    sudo apt install -y \
      gtk2-engines-pixbuf gtk2-engines-murrine \
      autoconf automake inkscape libgdk-pixbuf2.0-dev libglib2.0-dev \
      libxml2-utils pkg-config sassc parallel
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

if [[ ! -d "$HOME/gitrepos/plata-theme" ]]; then
  echo "cloning plata in $HOME/gitrepos/"
  mkdir -p ~/gitrepos/
  (cd ~/gitrepos/; git clone https://gitlab.com/tista500/plata-theme.git)
  GS_update_plata
fi
