#!/usr/bin/env bash

URL_RELEASE="https://data.services.jetbrains.com/products/releases?code=IIC&latest=true"
URL=$(wget $URL_RELEASE -q -O - | jq '.IIC[0].downloads.linux.link' -r)
DOWNLOADED_FILE="/tmp/ideaIC.tar.gz"
INSTALLATION_DIR="$HOME/Applications/idea"
DESKTOP_FILE="$HOME/.local/share/applications/jetbrains-idea-ce.desktop"

wget $(wget $URL_RELEASE -q -O - | jq '.IIC[0].downloads.linux.link' -r) -O $DOWNLOADED_FILE
mkdir -p $INSTALLATION_DIR
tar zxf $DOWNLOADED_FILE --strip-components=1 -C ~/Applications/idea
rm $DOWNLOADED_FILE
cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA Community Edition
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-idea-ce
EOL
echo "Exec=\"$INSTALLATION_DIR/bin/idea.sh\" %f" >> $DESKTOP_FILE
echo "Icon=$INSTALLATION_DIR/bin/idea.png" >> $DESKTOP_FILE
