#!/usr/bin/env bash

URL='https://download-test.robomongo.org/linux/robo3t-1.3.1-linux-x86_64-7419c406.tar.gz'
DOWNLOADED_FILE='/tmp/robo3t.tar.gz'
INSTALLATION_DIR="$HOME/Applications/robo3t"
DESKTOP_FILE="$HOME/.local/share/applications/robo3t.desktop"
EXECUTABLE_FULL_PATH="$INSTALLATION_DIR/bin/robo3t"


wget $URL -O $DOWNLOADED_FILE
mkdir -p $INSTALLATION_DIR
tar zxf $DOWNLOADED_FILE --strip-components=1 -C $INSTALLATION_DIR
rm $DOWNLOADED_FILE
cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=Robo3T
Icon=robo3t
Type=Application
StartupNotify=true
Keywords=mongo;robo3t;dev
StartupWMClass=robo3t
EOL
echo "Exec=\"$EXECUTABLE_FULL_PATH\"" >> $DESKTOP_FILE

mkdir -p ~/.local/share/icons
wget "https://raw.githubusercontent.com/Studio3T/robomongo/master/install/macosx/robomongo.iconset/icon_512x512.png" -O ~/.local/share/icons/robo3t.png
