#!/usr/bin/env bash

whatos() {
  if [[ -f /etc/os-release ]]; then
    (
      source /etc/os-release
      echo "${NAME}"
    )
    return
  fi

  if command -v lsb_release >/dev/null 2>&1; then
    lsb_release -is
    return
  fi

  echo ""
}

case "$(whatos)" in
  "Fedora" | "Fedora Linux")
    #sudo dnf remove docker \
    #                docker-client \
    #                docker-client-latest \
    #                docker-common \
    #                docker-latest \
    #                docker-latest-logrotate \
    #                docker-logrotate \
    #                docker-selinux \
    #                docker-engine-selinux \
    #                docker-engine
    sudo dnf -y install dnf-plugins-core
    sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf check-update
    sudo dnf -y install docker-ce docker-ce-cli containerd.io
    ;;
  "Ubuntu" | "Debian" | "LinuxMint" | "Pop")
    # sudo apt-get --purge --yes remove docker docker-engine docker.io containerd runc
    sudo apt-get install --assume-yes ca-certificates curl gnupg
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    _ARCH=
    ARCH="$(dpkg --print-architecture)"
    _CODE_NAME=
    _CODE_NAME="$(. /etc/os-release && echo "${VERSION_CODENAME}")"
    echo "deb [arch=${ARCH} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${_CODE_NAME} stable" |
      sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
    sudo apt-get update
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    ;;
  *)
    echo "this script does not have packages for this release"
    exit 1
    ;;
esac

echo "Installing group docker and adding the current user to it"
sudo groupadd docker || true
sudo usermod -aG docker "${USER}"
#newgrp docker

sudo systemctl enable docker.service
sudo systemctl enable containerd.service

echo -e "\e[1;32mDone\e[0m\n"

## to uninstall remove the packages and also:
# sudo rm -rf /var/lib/docker
# sudo rm -rf /var/lib/containerd
