#!/usr/bin/env bash

case "$(what-pm)" in
  "dnf" | "yum")
    install-remote-package 'https://download.cdn.viber.com/desktop/Linux/viber.rpm'
    ;;
  "apt")
    install-remote-package "https://download.cdn.viber.com/cdn/desktop/Linux/viber.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac
