#!/usr/bin/env bash

case "$(what-pm)" in
  "dnf")
    sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    sudo dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    sudo dnf install --assumeyes sublime-text
    ;;
  "apt")
    sudo apt-get install --assume-yes apt-transport-https
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
    echo "deb [arch=$(dpkg --print-architecture)] https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
    sudo apt-get update
    sudo apt-get install --assume-yes sublime-text
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac
