#!/usr/bin/env bash

# GO111MODULE=on go get -u -v github.com/cli/cli/cmd/gh@latest

URL=$(\
  curl --fail --silent --show-error --location https://api.github.com/repos/cli/cli/releases/latest \
  | \
  jq '.assets[] | select(.name | endswith("_linux_amd64.tar.gz")) | .browser_download_url' --raw-output \
)

URL=""
case "$(what-pm)" in
  "dnf")
    URL=$(curl --fail --silent --show-error --location https://api.github.com/repos/cli/cli/releases/latest | \
      jq '.assets[] | select(.name | endswith("_linux_amd64.rpm")) | .browser_download_url' --raw-output)
    ;;
  "apt")
    URL=$(curl --fail --silent --show-error --location https://api.github.com/repos/cli/cli/releases/latest | \
      jq '.assets[] | select(.name | endswith("_linux_amd64.deb")) | .browser_download_url' --raw-output)
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install-remote-package $URL
