#!/usr/bin/env bash

case "$(what-os)" in
  "Fedora")
    sudo rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey
    cat > /tmp/atom.repo << EOL
[Atom]
name=Atom Editor
baseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch
enabled=1
gpgcheck=0
repo_gpgcheck=0
gpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey
EOL

    sudo cp /tmp/atom.repo /etc/yum.repos.d/atom.repo
    rm /tmp/atom.repo
    sudo dnf -y install atom
    ;;
  "Ubuntu"|"Debian"|"LinuxMint"|"Pop")
    curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
    sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
    sudo apt update
    sudo apt install -y atom
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac
