#!/usr/bin/env bash

sudo test
URL=""
os_name=$(lsb_release -is)
case "$os_name" in
  "Fedora")
    URL="https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
    ;;
  "Ubuntu"|"Debian"|"LinuxMint")
    URL="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    ;;
  *)
    echo "this script does not have packages for this release"
    exit 1
    ;;
esac

install_remote_package $URL
