#!/usr/bin/env bash

URL=""
case "$(what-pm)" in
  "dnf")
    URL='https://go.skype.com/skypeforlinux-64.rpm'
    ;;
  "apt")
    URL='https://go.skype.com/skypeforlinux-64.deb'
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install-remote-package $URL
