#!/usr/bin/env bash

sudo apt-get install --assume-yes \
  git build-essential strace make cmake automake autoconf \
  vim nano \
  ack ripgrep \
  curl wget jq \
  htop lsb-release

sudo apt-get install --assume-yes \
  default-jre default-jre-headless \
  default-jdk-doc default-jdk default-jdk-headless \
  openjdk-8-jre openjdk-8-jre-headless \
  openjdk-8-doc openjdk-8-jdk openjdk-8-jdk-headless \
  openjdk-11-jre openjdk-11-jre-headless \
  openjdk-11-doc openjdk-11-jdk openjdk-11-jdk-headless \
  openjdk-17-jre openjdk-17-jre-headless \
  openjdk-17-doc openjdk-17-jdk openjdk-17-jdk-headless

# sudo update-java-alternatives --list
# sudo update-java-alternatives --set java-1.17.0-openjdk-amd64

sudo apt-get install --assume-yes ubuntu-restricted-addons
sudo apt-get install --assume-yes meld gitg gitk #pavucontrol

sudo systemctl stop ufw.service
sudo systemctl disable ufw.service

sudo apt install --assume-yes \
  dstat   \
  atop    \
  iotop   \
  ioping  \
  sysstat \
  nmon

