#!/usr/bin/env bash
sudo snap install atom --classic
sudo snap install code --classic
sudo snap install sublime-text --classic
sudo snap install intellij-idea-community --classic

sudo snap install postman
sudo snap install insomnia

sudo snap install skype --classic
sudo snap install telegram-desktop
sudo snap install slack --classic

sudo snap install spotify
sudo snap install chromium
sudo snap install opera

sudo snap install remmina

