FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y \
        build-essential \
        make \
        autoconf \
        automake \
        inkscape \
        libgdk-pixbuf2.0-dev \
        libglib2.0-dev \
        libxml2-utils \
        pkg-config \
        sassc \
        parallel
