#!/usr/bin/env bash

# https://man7.org/linux/man-pages/man1/find.1.html
# https://linux.die.net/man/1/find
# https://ss64.com/mac/find.html

# set -e
# set -u
# set -o pipefail

# -perm +111

find ./ \
  -type f \
  -and \( -not -path './.git/*' \) \
  -and \( -not -path './vendor/*' \) \
  -and \( -name '*.bash' -or -name '*.sh' -or -executable \) \
  -print0 | while IFS= read -r -d '' file; do
  if file "${file}" | grep -qE 'shell script|POSIX shell script|Bourne-Again shell script|bash script|a sh script'; then
    echo "${*} ${file}"
    "${@}" "${file}"
  fi
done
