#!/usr/bin/env bash

# https://man7.org/linux/man-pages/man1/find.1.html
# https://linux.die.net/man/1/find
# https://ss64.com/mac/find.html

# set -e
# set -u
# set -o pipefail

VERBOSE=${VERBOSE:="0"}

mapfile -d '' -t files < <(
  find ./ \
    -type f \
    -and \( -not -path './.git/*' \) \
    -and \( -name '*.bash' -or -name '*.sh' -or -perm /111 \) \
    -print0
)

status=0

for file in "${files[@]}"; do
  if file "${file}" | grep -qE 'shell script|POSIX shell script|Bourne-Again shell script|bash script|a sh script'; then
    [[ ${VERBOSE} == "1" ]] && echo "${*} ${file}"
    "${@}" "${file}" || status=1
  fi
done

exit ${status}
