#!/usr/bin/env bash

if ! command -v shellcheck &>/dev/null; then
  echo 'shellcheck not found' >&2
  exit 1
fi

[[ ${1} == "-v" ]] && export VERBOSE="1"

./.helpers/foreach-script shellcheck \
  --norc \
  --external-sources \
  --format=tty \
  --enable=require-variable-braces,add-default-case \
  --exclude=SC2012 \
  --exclude=SC2002 \
  --exclude=SC2059 \
  --exclude=SC2181

# SC2012 (info): Use find instead of ls to better handle non-alphanumeric filenames. https://www.shellcheck.net/wiki/SC2012
# SC2059 (info): Don't use variables in the printf format string. https://www.shellcheck.net/wiki/SC2059
# SC2002 (style): Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead. https://www.shellcheck.net/wiki/SC2002
# SC2181 (style): Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?. https://www.shellcheck.net/wiki/SC2181
