#!/usr/bin/env bash

if ! command -v shellcheck &> /dev/null; then
  echo 'shellcheck not found' >&2
  exit 1
fi

mapfile -t FILES < <(find . \
  \( -not -name 'root.bash' \) \
  -a \( -not -path './.git/*' \) \
  -a \( -not -path './config/gnome/lib/palettes/*' \) \
  -a \( -name '*.bash' -o \( -type f -a -executable \) \) \
  -print)

set -ex

shellcheck \
  --shell=bash \
  --exclude=SC1090 \
  --external-sources \
  --severity=warning \
  --format=tty \
  --norc \
  root.bash \
  "${FILES[@]}"
