#!/usr/bin/env bash

tools=(
    "golang.org/x/lint/golint"
    "golang.org/x/tools/cmd/guru"
    "golang.org/x/tools/cmd/gorename"
    "github.com/uudashr/gopkgs/cmd/gopkgs"
    "github.com/ramya-rao-a/go-outline"
    "github.com/acroca/go-symbols"
    "github.com/go-delve/delve/cmd/dlv"
    #"github.com/mdempsky/gocode"
    "github.com/stamblerre/gocode" #works with Go Modules.
    "github.com/rogpeppe/godef"
    "github.com/sqs/goreturns"
)


for t in "${tools[@]}"
do
  echo "Installing $t"
  #go get -u $t
done

unset t
unset tools
