#!/usr/bin/env bash

cat << EOL | sudo tee /etc/sysctl.d/98-file-max.conf
fs.file-max = 65535
EOL

cat << EOL | sudo tee /etc/sysctl.d/98-inotify.conf
fs.inotify.max_user_watches = 524288
EOL

cat << EOL | sudo tee /etc/sysctl.d/98-vm.conf
vm.max_map_count = 262144
EOL

cat << EOL | sudo tee /etc/sysctl.d/98-swappiness.conf
vm.swappiness = 35
EOL


sudo sysctl -p --system
sudo systemctl restart systemd-sysctl.service
#cat /proc/sys/fs/inotify/max_user_watches
#cat /proc/sys/vm/max_map_count
#cat /proc/sys/vm/swappiness
