#!/usr/bin/env bash

MY_NAME=$(whoami)
MY_ID=$(id -u $MY_NAME)
MY_GROUP=$(id -ng $MY_NAME)
MY_GID=$(id -g $MY_NAME)

echo "User : $MY_NAME $MY_ID"
echo "Group: $MY_GROUP $MY_GID"

docker build -f Dockerfile . \
  --build-arg NEW_USER="$MY_NAME" \
  --build-arg NEW_USER_ID="$MY_ID" \
  --build-arg NEW_GROUP="$MY_GROUP" \
  --build-arg NEW_GROUP_ID="$MY_GID" \
  -t user-fedora:latest
