#!/usr/bin/env bash

cat <<EOF >~/.gitconfig
[user]
	name = Kostas Stamatakis
	email = moukoublen@gmail.com
	signingkey = C970F7797ADA3FABFB9A0786A0A88AF285F7E69B

[include]
	path = ${DOTFILES_PATH}/config/git/main.gitconfig
EOF
