#!/usr/bin/env bash

(cd ~/gitrepos/bibata/Bibata_Cursor/; git reset --hard)
(cd ~/gitrepos/bibata/Bibata_Extra_Cursor/; git reset --hard)

rm -rf ~/gitrepos/bibata/out
mkdir ~/gitrepos/bibata/out

docker run \
  --rm \
  --interactive \
  --tty \
  --volume "${HOME}/gitrepos/bibata/Bibata_Cursor:/tmp/bibata/Bibata_Cursor" \
  --volume "${HOME}/gitrepos/bibata/Bibata_Extra_Cursor:/tmp/bibata/Bibata_Extra_Cursor" \
  --volume "${HOME}/gitrepos/bibata/out:/tmp/bibata/out" \
  --workdir /tmp/bibata \
  bibata-builder \
  bash -c "cd Bibata_Cursor; ./build.sh; ./install.sh; cd ../Bibata_Extra_Cursor; ./build.sh; ./install.sh; cp -r \$HOME/.icons/* /tmp/bibata/out"
