#!/usr/bin/env bash

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_PATH="${HOME}/.config/sublime-text/Packages/User"
# if [[ $(uname) = "Darwin" ]]; then
#   CONF_PATH="${HOME}/.config/sublime-text/Packages/User"
# fi
mkdir -p "${CONF_PATH}"

lnx "${SRC}/Preferences.sublime-settings" "${CONF_PATH}/Preferences.sublime-settings"
