#!/usr/bin/env bash
sudo dnf -y install \
  aajohan-comfortaa-fonts \
  adobe-source-code-pro-fonts \
  google-roboto-condensed-fonts \
  google-roboto-fonts \
  google-roboto-mono-fonts \
  google-roboto-slab-fonts \
  mozilla-fira-fonts-common \
  mozilla-fira-mono-fonts \
  mozilla-fira-sans-fonts \
  open-sans-fonts \
  overpass-fonts \
  overpass-mono-fonts \
  oxygen-fonts \
  oxygen-fonts-common \
  oxygen-mono-fonts \
  oxygen-sans-fonts \
  levien-inconsolata-fonts
