#!/usr/bin/env bash

sudo test
URL=""
os_name=$(lsb_release -is)
case "$os_name" in
  "Fedora")
    URL='https://go.skype.com/skypeforlinux-64.rpm'
    ;;
  "Ubuntu"|"Debian"|"LinuxMint")
    URL='https://go.skype.com/skypeforlinux-64.deb'
    ;;
  *)
    echo "this script does not have packages for this release"
    ;;
esac

install_remote_package $URL
