#!/usr/bin/env bash

URL='https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US'
DOWNLOADED_FILE='/tmp/firefox-dev.tar.bz2'
INSTALLATION_DIR="$HOME/Applications/firefox-dev"
DESKTOP_FILE="$HOME/.local/share/applications/firefox-developer.desktop"
EXECUTABLE_FULL_PATH="$INSTALLATION_DIR/firefox"


wget $URL -O $DOWNLOADED_FILE
mkdir -p $INSTALLATION_DIR
tar jxf $DOWNLOADED_FILE --strip-components=1 -C $INSTALLATION_DIR
rm $DOWNLOADED_FILE
cat > $DESKTOP_FILE <<EOL
[Desktop Entry]
Version=1.0
Encoding=UTF-8
Name=Firefox Developer Edition
Comment=Firefox Developer Edition
Icon=firefox-developer-edition
Type=Application
StartupNotify=true
Keywords=firefox;dev;browser
Categories=Internet
EOL
echo "Exec=\"$EXECUTABLE_FULL_PATH\"" >> $DESKTOP_FILE
