name: shell-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: install shellcheck and bash
      run: sudo apt-get install -y shellcheck bash

    - uses: mfinelli/setup-shfmt@v3

    - name: run shellcheck anf shfmt
      shell: bash
      run: |
        set -e
        ./.helpers/sh-checks
        ./.helpers/git-check-dirty
